# Generated by Django 3.0.4 on 2020-04-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_memes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memes',
        ),
    ]
