# Generated by Django 3.0.4 on 2020-04-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_delete_memes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
